version: '3'

services:
  simulation:
    build: .
    image: gps-no-simulation:latest
    container_name: gps-no-simulation
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
